// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.20.3
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface PaginationDto {
  page: number;
  skip: number;
  limit: number;
}

export interface User {
  id: number;
  name: string;
  email: string;
  socialMedia: SocialMedia | undefined;
}

export interface CreateUserDto {
  name: string;
  email: string;
  socialMedia: SocialMedia | undefined;
}

export interface UpdateUserDto {
  id: number;
  name: string;
  socialMedia: SocialMedia | undefined;
}

export interface Id {
  id: number;
}

export interface Empty {
}

export interface UserList {
  users: User[];
}

export interface SocialMedia {
  facebook?: string | undefined;
  twitter?: string | undefined;
  instagram?: string | undefined;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface UserServiceClient {
  createUser(request: CreateUserDto): Observable<User>;

  findUserById(request: Id): Observable<User>;

  getAllUsers(request: Empty): Observable<UserList>;

  updateUser(request: UpdateUserDto): Observable<User>;

  deleteUser(request: Id): Observable<Empty>;

  queryUsers(request: Observable<PaginationDto>): Observable<User>;
}

export interface UserServiceController {
  createUser(request: CreateUserDto): Promise<User> | Observable<User> | User;

  findUserById(request: Id): Promise<User> | Observable<User> | User;

  getAllUsers(request: Empty): Promise<UserList> | Observable<UserList> | UserList;

  updateUser(request: UpdateUserDto): Promise<User> | Observable<User> | User;

  deleteUser(request: Id): Promise<Empty> | Observable<Empty> | Empty;

  queryUsers(request: Observable<PaginationDto>): Observable<User>;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createUser", "findUserById", "getAllUsers", "updateUser", "deleteUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = ["queryUsers"];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
