// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.20.3
// source: proto/user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface User {
  id: number;
  name: string;
  email: string;
  /** ✅ Important */
  password: string;
  role: string;
}

export interface CreateUserDto {
  name: string;
  email: string;
  /** ✅ Important */
  password: string;
  role: string;
}

export interface UpdateUserDto {
  id: number;
  name: string;
  role: string;
}

export interface UpdateUserRoleDto {
  id: number;
  role: string;
}

export interface Id {
  id: number;
}

export interface Empty {
}

export interface UserList {
  users: User[];
}

export interface FindUserByEmailRequest {
  email: string;
}

export interface UserResponse {
  user: User | undefined;
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  createUser(request: CreateUserDto): Observable<User>;

  findUserById(request: Id): Observable<User>;

  getAllUsers(request: Empty): Observable<UserList>;

  updateUser(request: UpdateUserDto): Observable<User>;

  updateUserRole(request: UpdateUserRoleDto): Observable<User>;

  deleteUser(request: Id): Observable<Empty>;

  findUserByEmail(request: FindUserByEmailRequest): Observable<UserResponse>;
}

export interface UserServiceController {
  createUser(request: CreateUserDto): Promise<User> | Observable<User> | User;

  findUserById(request: Id): Promise<User> | Observable<User> | User;

  getAllUsers(request: Empty): Promise<UserList> | Observable<UserList> | UserList;

  updateUser(request: UpdateUserDto): Promise<User> | Observable<User> | User;

  updateUserRole(request: UpdateUserRoleDto): Promise<User> | Observable<User> | User;

  deleteUser(request: Id): Promise<Empty> | Observable<Empty> | Empty;

  findUserByEmail(request: FindUserByEmailRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createUser",
      "findUserById",
      "getAllUsers",
      "updateUser",
      "updateUserRole",
      "deleteUser",
      "findUserByEmail",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
