// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.20.3
// source: proto/product.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "products";

export interface Product {
  id: number;
  name: string;
  description: string;
  price: number;
  stock: number;
}

export interface CreateProductDto {
  name: string;
  description: string;
  price: number;
  stock: number;
}

export interface UpdateProductDto {
  id: number;
  name: string;
  description: string;
  price: number;
  stock: number;
}

export interface Id {
  id: number;
}

export interface Empty {
}

export interface ProductList {
  products: Product[];
}

export const PRODUCTS_PACKAGE_NAME = "products";

export interface ProductServiceClient {
  createProduct(request: CreateProductDto): Observable<Product>;

  findProductById(request: Id): Observable<Product>;

  getAllProducts(request: Empty): Observable<ProductList>;

  updateProduct(request: UpdateProductDto): Observable<Product>;

  deleteProduct(request: Id): Observable<Empty>;
}

export interface ProductServiceController {
  createProduct(request: CreateProductDto): Promise<Product> | Observable<Product> | Product;

  findProductById(request: Id): Promise<Product> | Observable<Product> | Product;

  getAllProducts(request: Empty): Promise<ProductList> | Observable<ProductList> | ProductList;

  updateProduct(request: UpdateProductDto): Promise<Product> | Observable<Product> | Product;

  deleteProduct(request: Id): Promise<Empty> | Observable<Empty> | Empty;
}

export function ProductServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createProduct",
      "findProductById",
      "getAllProducts",
      "updateProduct",
      "deleteProduct",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCT_SERVICE_NAME = "ProductService";
